spring:
  application:
    name: space

  datasource:
    url: jdbc:postgresql://db.riyavwrbzsdcqibpifix.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

  flyway:
    enabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
    default-schema: flyway

logging:
  level:
    org.springframework.web: DEBUG