CREATE SEQUENCE IF NOT EXISTS public.SEQ_PROJETO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS public.SEQ_VAGAS START WITH 1 INCREMENT BY 1;

CREATE TABLE projeto (
    id INTEGER PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao VARCHAR(2000) NOT NULL,
    quantidade_vagas INTEGER NOT NULL,
    status VARCHAR(50) NOT NULL
);

CREATE TABLE Vagas(
    id INTEGER PRIMARY KEY,
    cargo VARCHAR(255) NOT NULL,
    quantidade INTEGER NOT NULL,
    projeto_id INTEGER NOT NULL,

    FOREIGN KEY(projeto_id) REFERENCES projeto(id)
);