CREATE SEQUENCE IF NOT EXISTS public.SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS public.SEQ_USUARIO_HIST START WITH 1 INCREMENT BY 1;

CREATE TABLE USUARIO(
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(255),
    CARGO VARCHAR(255),
    EMAIL VARCHAR(255),
    SENHA VARCHAR(255),
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

CREATE TABLE USUARIO_HIST(
    ID    INTEGER NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    TIPO_ALTERACAO VARCHAR(20),
    FK_USUARIO INTEGER NOT NULL,
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(ID)
);

